version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - PORT=3000
      - TOKEN_KEY=${TOKEN_KEY}
      - MONGO_URI=${MONGO_URI}
      - DEBUG=${DEBUG}
      - NODE_ENV=${NODE_ENV}
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    
volumes:
  mongo: